- hosts: servers
  become: yes
  become_method: sudo
  tasks:
   - name: updates a server
     apt: update_cache=yes
   - name: upgrade a server
     apt: upgrade=dist
          autoremove=yes
   - name: reboot servers
     shell: sleep 2 && shutdown -r now "Ansible reboot"
     async: 1
     poll: 0
     ignore_errors: true        
   - name: wait
     local_action: 
       wait_for host={{ inventory_hostname }} 
       state=started port=22 delay=5 timeout=300 connect_timeout=15
     become: false